# Votre titre

## Abstract
> Rédigez ici votre abstract (en anglais).

## Résumé
> Rédigez ici votre résumé (en français)

>**Keywords**
Écrire ici vos mots-clés

## Introduction

La question des déchets est associée, avec un engouement renouvelé, à d’autres enjeux environnementaux, tels que les différentes limites planétaires, notamment dû à l’émergence et au développement accéléré, depuis la décennie 2010, d’un nouveau paradigme de production et de consommation des ressources, l’économie circulaire [@circle_economy_leconomie_2024; @marty_histoire_2023, Graphique 1]. Celle-ci se veut une réponse directe aux impératifs de remise en question des activités productives humaines énoncées en 1972 par le rapport *The Limits to Growth du Club de Rome* [@meadows_limits_1972] et aux cibles de l’objectif de développement durable (ODD) 12 des Nations Unies *Consommation et production responsables* [@organisation_des_nations_unies_objectif_nodate]. Le régime international de la gestion des déchets fait ainsi l’objet de pressions accrues pour tenter de répondre à un éventail plus large de problématiques, mais surtout pour réduire la quantité de déchets produites. Alors que la prise en charge de ces nouvelles demandes se traduit par des changements techniques, elle questionne également la définition de la notion de déchets, qui demeure inchangée, semblant ainsi démontrer la présence d’enjeux politiques et non seulement techniques à la gestion des déchets. Cet essai vise à mieux comprendre la définition de la notion de déchets dans le régime international, la façon dont celle-ci se construit et évolue à travers un contexte international changeant. Cet essai prendra pour cas d’étude la *Convention de Bâle sur le contrôle des mouvements transfrontières de déchets dangereux et de leur élimination*, convention centrale du régime international des déchets.

## Question de recherche

Les changements de paradigmes environnementaux précédemment mentionnés soulèvent l’importance de la définition de la notion de déchets dans le cadrage des efforts internationaux pour atteindre les objectifs du développement durable. Dans un contexte d’encadrement, sans définition pour dessiner les contours de ce que cible une norme, celle-ci est relativement inefficace, puisqu’il lui est impossible de normaliser son application, d’exercer une supervision et d’évaluer les performances [@pongracz_evolving_2004, 473]. L’essence du rôle d’une définition relève du fait qu’elle est le référent de l’encadrement de la conduite des acteurs [@cheyne_fitting_1995, 149]. En soulevant que cette définition dépasserait le simple enjeu technique, il apparaît essentiel d’étudier celle-ci à travers le prisme des relations internationales pour bien comprendre les dynamiques politiques à l’œuvre. Effectivement, dans une perspective de réduction des déchets, comme déclarée par les Nations Unies, les attentes envers la définition de déchets semblerait dépasser celles propres à une norme régulatrice et constitutive, pour possiblement devenir correspondre à celles d’une norme évaluative permettant de juger la façon dont les déchets sont administrés. Ce type de normes demeure sous-étudié, alors qu’il est celui le plus pertinent pour juger des comportements des acteurs nationaux [@finnemore_international_1998, 891-892]. En ce sens, l’essai qui suit cherchera à comprendre comment se construit la norme de déchets dans l’espace international à travers les interactions entre les législations internationales et les législations nationales.

## Cadre théorique

### Définition d’une norme

Une norme est comprise, selon Finnemore et Sikkink, comme un «standard of appropriate behavior for actors with a given identity», et est à distinguer de l’institution de par le caractère unique de la norme en contraste avec celui agrégé de l’institution, les deux termes étant parfois employés indistinctement [@finnemore_international_1998, 891]. Les normes sont catégorisées en trois types, soit les normes dites «regulative[s]» qui visent à «order and constrain behavior», les normes dites «constitutive[s]» qui visent à «create new actors, interests or categories of action» et les normes «evaluative[s] or prescriptive[s]» qui visent à évaluer la «quality of "oughtness"» des actions [@finnemore_international_1998, 891-892]. Le contenu des normes se construit autour d’un ensemble de propriétés incluant, mais pas exclusivement, les problématiques auxquelles elles sont rattachées ou qu’elles cherchent à définir, les valeurs et les principes qui y sont intrinsèquement liées, les comportements qu’elles supposent ou requièrent des acteurs qui les suivront, leur degré de précision, etc. [@hadden_whats_2016, 253-254; @loges_not_2020, 1011].

### Cycle de vie d’une norme

Les normes s’implémentent à travers un cycle de vie se déroulant en trois phases successives, soit l’émergence, la cascade et l’internalisation. L’émergence est une phase de construction où les entrepreneurs normatifs développent une nouvelle norme à partir d’une prise de conscience de qui devrait être ou ne devrait pas être en contraste avec la réalité des comportements internationaux en la matière. Ils se doivent ensuite de procéder à un framing, ici compris comme un cadrage, de la norme pour la présenter aux acteurs externes à la construction. Une fois le contenu et le discours de la norme conçus ceux-ci doivent être intégrés à une plateforme de promotion de la norme, outil communicatif pour convaincre à l’adhésion. Une fois cette opération de persuasion enclenchée, la norme se trouve en attente de l’atteinte de son institutionnalisation. Celle-ci se comprend comme son intégration dans des règles et des institutions à l’international, étape qui est essentielle pour basculer à la prochaine étape du cycle de vie. Le seuil de l’institutionnalisation serait à l’adhésion d’environ le tiers des États à la norme, l’approximation découlant du poids variable des États, certains États étant critiques pour faire basculer la norme vers la seconde étape de son cycle [@finnemore_international_1998, 892-893, 895-896 et 898-901].

La cascade de la norme est une étape de propagation où la norme doit se diffuser auprès des acteurs qui ne l’ont toujours pas adoptée, à travers différents types de pressions de socialisation entre les États et les endosseurs normatifs. Face à ces pressions pour adopter la norme, les États auront tendance à s’approprier la norme pour des motifs de légitimation du rôle et du statut d’État à l’échelle internationale, de conformité pour justifier leurs comportements ou pour l’estime pour s’assurer le respect de leurs vis-à-vis et favoriser une perception positive de leur État par les acteurs sur la scène internationale [@finnemore_international_1998, 902-904].

Une fois que la norme a suffisamment percolé dans le système international et qu’elle est désormais intégrée et prise pour acquis, la troisième et dernière étape du cycle de vie la norme s’enclenche. Il faut noter que contrairement à la précédente transition, il n’y a pas d’indicateur clair de la fin d’une cascade d’une norme et du début de son internalisation. L’internalisation constitue la progression vers un stade où la norme est profondément acceptée, se traduisant par son retrait des débats politiques et son importance de plus en plus diminuée comme sujet de recherche. Son intégration peut être si profonde que la norme peut devenir de moins en moins discernable dans les relations internationales. Il faut cependant prendre en considération que l’atteinte de ce niveau ne signifie pas que la norme n’est plus influente. Au contraire, elle peut l’être encore plus fortement, de l’impossibilité de véritablement saisir les canaux de son application et d’ainsi en contrôler les impacts [@finnemore_international_1998, 904-905].

### Émergence de la norme

Pour émerger, une norme doit réussir à dépasser l’inertie inhérente des sociétés qui vise la conservation d’une stabilité des systèmes politico-économico-juridiques, force statique qui ne doit pas être négligée. Pour qu’un État choisisse de construire une nouvelle norme, un besoin doit être ressenti pour un changement législatif au sein de l’État et celui-ci doit être l’objet d’importantes forces de pressions internes pour être l’initiateur de ce changement [@watson_comparative_1978, 330-333]. 

Le travail de construction normatif qui suit peut, mais ne doit pas être compris comme un travail de création complet. La proposition contemporaine de nouvelles normes se réalise dans un environnement juridique international déjà fortement chargé. Il s’agit donc plutôt d’un travail incrémentiel à partir des normes existantes [@florini_evolution_1996, 376-377; @moore_negotiating_2012, 41]. Ainsi, le contenu d’une norme peut être élaboré à travers différent processus comme l’hybridation, consistant à réaliser des concessions en vue d’adjoindre des normes autrement compétitives ou contradictoires [@moore_negotiating_2012, 42], la fusion, où deux normes provenant de deux domaines différents sont jointes pour créer une nouvelle norme, le greffage, où une nouvelle norme est greffée à une norme existante dans le même domaine pour faciliter son institutionnalisation, et la résonnance, où une norme est modifiée pour être en phase avec le ou les discours existants influents [@acharya_how_2004, 243-244; @gonenc_conceptualizing_2021, 446; @price_reversing_1998, 617, 628 et 630]. À ce sujet, Bloomfield critique les théories traditionnelles sur l’évolution des normes en insistant que les procédures de leur développement ne sont pas le seul repositoire du dynamisme normatif, mais que le contenu même des normes est dynamique et non statique [@bloomfield_norm_2016, 313; @moore_negotiating_2012, 33]. L’élaboration du contenu d’une norme doit donc être comprise comme des démarches variables, itératives, dynamiques et non uniformes qui peuvent être mobilisées tant pour la définition de nouvelles normes que pour la redéfinition de normes existantes, par leur approfondissement tant en termes de contenu qu’en termes d’intégration [@gonenc_conceptualizing_2021, 446-448; @hadden_whats_2016, 261].

### Cascade des normes

Comme spécifié par Finnemore et Sikkink, la cascade d’une norme ne peut s’entamer que lorsque la norme est institutionnalisée. La manière la plus aisée de constater ce point de bascule est à travers la juridiction internationale où les traités sont les principaux véhicules normatifs et agissent comme les proxies les plus accessibles en recherche pour observer la diffusion d’une norme [@finnemore_international_1998, 900-901]. L’implantation des traités, définie comme «the adoption of legal measures by states to translate their international commitments in their domestic legal order», peut généralement être évaluée à travers l’étude de la ratification des différentes composantes des traités ou des législations nationales [@brandi_when_2019, 15; @weiss_engaging_2000, 4]. 

Cette cascade normative est comprise comme un phénomène de convergence des politiques, concept que Bennett définit en cinq temps, dans sa revue de littérature sur la question, en insistant sur les différents objets de la convergence des politiques: 
> First, it can signify a convergence of policy goals, a coming together of intent to deal with common policy problems. Secondly, it can refer to policy content, defined as the more formal manifestations of government policy - statutes, administrative rules, regulations, court decisions and so on. Thirdly, there may be a convergence on policy instruments, i.e. the institutional tools available to administer policy, whether regulatory, administrative or judicial. Fourthly, convergence may occur on policy outcomes, impacts or consequences - the results (positive or negative, effective or ineffective) of implementation. Finally, there may be a convergence of policy style, a more diffuse notion signifying the process by which policy responses are formulated (consensual or conflictual, incremental or rational, anticipatory or reactive, corporatist or pluralist, etc.) [@bennett_what_1991, 218].

Cette convergence peut se produire à travers des modalités variées, présentées exhaustivement dans le modèle de continuum de Dolowitz et Marsh, ayant évolué en une catégorisation plus succincte en trois mécanismes, soit l’imposition, l’harmonisation et la diffusion [@dolowitz_learning_2000, 9]. L’imposition est comprise comme l’adoption d’une norme provoquée par des situations de coercition politique ou économique où «external actors intentionally force nations to adopt policy innovations which they would not have adopted otherwise and do so by exploiting economic or political power asymmetries» [@busch_international_2005-1, 863-864]. L’harmonisation, quant à elle, est une démarche ancrée dans les mécanismes de mise en place de traités comme la négociation, la juridicisation et l’encadrement qui se comprend comme «a multilateral and state-centred process where international negotiations among sovereign states and subsequent  policy formulation lead to domestic implementation and compliance[, where t]he same states that create the regulations are also responsible for their implementation» [@busch_international_2005-1, 863]. Finalement, la diffusion est quant à elle le mécanisme ayant été théorisé le plus récemment dans la littérature comprise comme «an international spread of policy innovations driven by information flows rather than by hierarchical or collective decision-making within international institutions [that are] adopted voluntarily by an increasing number of countries over time» [@busch_international_2005-1, 865], dont les mécanismes principaux sont l’apprentissage, la compétition, l’imitation, l’émulation et la socialisation [@marsh_policy_2009, 271-274].

Alors que l’imposition et l’harmonisation se caractérisent par une dynamique de convergence top-down, la diffusion est quant à elle davantage bottom-up, au sens où les normes peuvent se diffuser horizontalement entre les États, mais aussi verticalement des États vers le supranational et vice-versa. De plus, alors que les rôles des parties prenantes de l’imposition ou de l’harmonisation sont facilement attribuables ou identifiables, la diffusion a de particulier que son efficacité varie en fonction de la véhémence de la promotion internationale de la norme effectuée et des acteurs internationaux qui choisissent d’y participer [@busch_global_2005, 164]. Ces mécanismes ne sont pas mutuellement exclusifs dans leur application, de là leur compréhension comme un continuum, des études démontrant par exemple que la coercition hiérarchique peut fonctionner en parallèle de l’apprentissage régional [@daley_horizontal_2005; @dobbin_global_2007, 461; @dolowitz_learning_2000, 9].

Concernant la diffusion, alors que les théories à son endroit insistent principalement sur la socialisation où les États sont influencés par les choix des autres États, Dobbin, Simmons et Garrett rappellent l’importance de prendre en compte les théories de l’apprentissage dans la compréhension de la diffusion. Les États apprendraient de leurs propres expériences de même que celles de leurs pairs avant d’adopter certaines normes ou non. L’apprentissage à travers les pairs se ferait tout particulièrement à travers la participation conjointe des États aux institutions internationales, de là la non-exclusivité des formes de convergence avec un lien entre harmonisation et diffusion [@dobbin_global_2007, 449-450 et 460-461; @haas_why_1979].

En terminant, à travers l’ensemble de ces processus et mécanismes, la cascade d’une norme ne peut se solder par une réussite que si son cadrage ou framing est réussi. On comprend le cadrage comme un exercice de: « […] selection and salience. To frame is to select some aspects of a perceived reality and make them more salient in a communicating text, in such a way as to promote a particular problem definition, causal interpretation, moral evaluation, and/or treatment recommendation for the item described.» [@entman_framing_1993, 52]. En ce sens, peu importe les procédures employées, celles-ci ne peuvent être productives que si elles sont soutenues par un exercice de présentation, de communication, efficace. Parmi les composantes de cette communication, la réussite de la cascade normative reposerait fortement sur la liaison de la norme a des problèmes concrets vécus par les possibles adhérents et non simplement sur une présentation de la norme comme une aspiration morale [@blondeel_what_2019, 64; @gonenc_conceptualizing_2021, 445]. 

### Internalisation

L’internalisation représente à la fois la dernière étape du cycle de vie d’une norme et l’atteinte d’un stade d’acceptation d’une norme où celle-ci ne fait plus l’objet de contestations, tout en se rappelant qu’il ne s’agit pas d’une fin en soi vu le dynamisme intrinsèque aux notions normatives [@bloomfield_norm_2016, 313; @finnemore_international_1998, 904]. L’internalisation est en principe corrélée au respect et à la conformité de la norme, qui dépasse l’implantation normative en s’attardant sur l’application concrète des dispositions prises lors de l’adhésion à la norme. Ce phénomène étant difficile à observer empiriquement, il reste possible de s’attarder sur les facteurs qui en facilitent la mise en œuvre ou, au contraire, qui l’empêchent [@weiss_engaging_2000, 4].

Une pléthore de facteurs pouvant jouer sur la réussite ou l’échec de l’internalisation de dispositions législatives sont proposés par les auteurs et peuvent être divisés entre des facteurs internes aux États et des facteurs externes. À l’interne, Berkowitz, Pistor et Richard insistent sur la famille légale à laquelle appartient l’État, le PIB par capita, la favorabilité de la loi aux investissements, une demande pour la disposition légale reliée à des incitatifs pour les citoyens de s’en saisir et ainsi à des incitatifs pour le système juridique à se l’approprier, une compréhension facile de celles-ci et une adéquation avec les valeurs de la société [@berkowitz_transplant_2003, 166-177]. Watson souligne également l’importance du besoin ressenti pour le changement législatif et ajoute le facteur discrétionnaire versus le facteur de généralité qui, selon lui, conditionnent tout deux l’application d’une disposition législative [@watson_comparative_1978, 328-332]. Marsh et Sharman rappellent quant à eux la variabilité des points de bascule des États et donc de leur résistance à la pression [@marsh_policy_2009, 273-274]. Les capacités respectives des États de même que leurs contextes économiques et sociaux respectifs et les changements qui pourraient les modifier sont quant à eux amenés comme des facteurs de respect ou non d’une norme pour les États par Downs, Rocke et Barsoom [@downs_is_1996, 380-381]. Terzi se concentre sur les adhésions à de normes multiples au sein des États qui peuvent mener à des conflits lors de l’avènement de nouvelles normes; les réflexes heuristiques des États sont alors à surveiller pour mieux comprendre leurs choix d’application normative [@terzi_emotional_2024]. Pour Stalley, le niveau de développement des États est critique dans leur positionnement face aux normes émergentes [@stalley_norms_2018].

À l’externe, parmi les facteurs issus du contexte international, Wiener souligne le rôle des puissances politiques, la complexité du problème auquel veut s’attaquer la norme, le caractère transfrontalier de la problématique, la quantité d’expériences nationales de la norme et la structure organisationnelle coordonnant l’application de la norme [@wiener_something_2000, 1355-1368]. D’un autre côté, Downs, Rocke et Barsoom, s’attardant sur le respect des traités, identifient la précision du texte, le contexte économique mondial, la présence ou l’absence de mécanismes de règlement des différends, la disponibilité ou non d’assistance technique et financière, les objectifs des traités et les efforts demandés qui y sont associés et les conséquences associées au non-respect du traité [@downs_is_1996, 380-386]. 

Toujours à l’externe, concernant la norme en soit, Finnemore et Sikkink proposent hypothétiquement la légitimation internationale de la norme, sa prééminence sur la scène internationale, le contexte international ou l’époque, les relations de la nouvelle norme avec les normes existantes et les caractéristiques ou propriétés intrinsèques de la norme [@finnemore_international_1998, 906-909]. Ce dernier facteur est également considéré par Loges et Jakobi comme influent sur l’adhésion à une norme [@loges_not_2020, 1011]. Moore quand à elle insiste sur les éléments suivants, à la fois liés à la norme et à ses entrepreneurs normatifs : « the authority or perceived legitimacy of the actor promoting the norm; the degree to which the norm “ats” or resonates with the dominant norm-complex; the skill of norm articulation by the norm-entrepreneur; […]; and the norm’s at with key actors’ identities.» [@moore_negotiating_2012, 33].

Malgré l’identification des facteurs pouvant favoriser l’internalisation d’une norme, des impasses se présentent tout de même sous deux formes habituelles. Tout d’abord, une norme peut se trouver dans une situation de déficit d’implantation, c’est-à-dire qu’elle reste au niveau du discours et ne se traduit pas en pratique [@hadden_whats_2016, 253]. D’un autre côté, une norme peut vivre un déficit de légitimité, c’est-à-dire que la norme en soit n’est pas contestée, mais que les procédures requises pour la mettre en place le sont [@bloomfield_norm_2016, 315; @wiener_theory_2014, 33-44]. Un manque de compréhension concernant ces cas de résistance à la propagation des normes persiste dans la littérature, comme le critique Bloomfield. Ce dernier recommande de prendre en compte tout le spectre des acteurs impliqués dans le cycle de vie d’une norme, de l’entrepreneur normatif à l’anti-preneur normatif, puisque ces derniers peuvent en parallèle se lancer dans un cycle de contestation de la norme dont les actions entreprises varieront en fonction de l’étape du cycle de vie dans laquelle se trouve la norme contestée [@bloomfield_norm_2016, 315-323]. Il apparaît également nécessaire de s’attarder au domaine de la norme. Les enjeux globaux, impliquant des coûts sociaux importants et présentant une certaine dangerosité sont moins à même d’inciter les États à mettre en place des changements nationaux, malgré la présence de dispositions internationales en la matière. En environnement, ce serait notamment le cas pour la question des déchets, où la variation dans les législations nationales suite à des ajouts légaux internationaux serait de 7.3%, un coefficient parmi les plus faibles en environnement [@brandi_when_2019, 31], bien que d’autres études soulignent le suivi d’une courbe normale moyenne de la diffusion des normes pour la questions des déchets [@busch_international_2005, 86]. Downs, Rocke et Barsoom soulignent que la difficulté à assurer le respect et la coopération de normes à l’échelle internationale varierait en fonction de l’approche des relations internationales associée au domaine en question. Les traités environnementaux auraient ainsi tendance à faire preuve de moins profondeur législative et ainsi à contraindre moins efficacement les actions des signataires par la multiplicité des approches auxquels ils peuvent se rattacher, en comparaison avec des traités sur la sécurité qui sont habituellement associés à l’approche réaliste. La pollution transfrontalière, comme les déchets, serait, entre autres, l’un des enjeux où cette réalité serait plus prégnante [@downs_is_1996, 391-398].

Plusieurs auteurs soulignent également l’impact des dynamiques Nord-Sud sur l’évolution d’une norme, soulignant comment des redéfinitions de normes, notamment des approfondissements, peuvent être clivantes ou polarisantes dans les relations entre le Nord et le Sud, tout en étant à la fois solidarisantes dans le Nord et dans le Sud [@hadden_whats_2016, 261]. De plus, des tendances différenciées sont associées au Nord et au Sud sur la question des impacts des accords environnementaux. Les accords auraient une corrélation plus élevée avec des changements législatifs nationaux dans les pays en développement, alors que les pays développés effectueraient seulement des changements dans leurs législations nationales en lien avec des accords environnementaux internationaux quand ils ont des vis-à-vis à fort revenu également. Certaines tendances communes quant aux traités seraient tout de même observables, comme le fait que les accords environnementaux auraient seulement un effet avant la signature, puisque les États auraient tendance à s’engager principalement dans des traités pour lesquels ils ont déjà passé de la législation au niveau national [@brandi_when_2019, 28-37]. Il demeure cependant qu’une opposition persiste entre le Nord et le Sud sur leur vision des problématiques environnementales; les pays du Nord chercheraient à gérer les problèmes environnementaux sans faire obstacle à l’économie, alors que les pays du Sud s’engageraient davantage dans des entreprises normatives visant à redéfinir les enjeux dans le but de s’attaquer plus frontalement à ceux-ci en établissant des responsabilités [@stalley_norms_2018, 143-146].

Finalement, malgré la réussite d’une convergence politique internationale autour d’une norme, Wiener rappelle la difficulté à étudier les dynamiques qui mènent aux différents échanges normatifs entre le niveau national et supranational, étant donné les tabous qui persistent sur les emprunts légaux. En effet, bien que les emprunts verticaux soient relativement fréquents, ceux qui ont lieu des législations nationales vers les traités internationaux sont souvent peu discutés et non indiqués dans ces derniers de peur de manquer à la neutralité ou à la légitimité de ce qui est conçu comme un traité. Lorsqu’un traité international adopte une norme généralement acceptée par les États, le tout est généralement perçu comme une extension de la diffusion horizontale et est accepté. Cependant, lorsqu’un traité procède à l’emprunts de notions qui sont propres à une ou à un petit groupe de législations, le tout est généralement camouflé ou non divulgué par peur de démontrer du favoritisme envers le ou les États d’origine et d’ainsi nuire à l’adhésion d’autres États au traité. Il y a généralement beaucoup de pression contre les emprunts internationaux de normes nationales ou pour éviter d’être transparent à ce sujet lorsque c’est fait, pour éviter de faire entrave à des négociations bien souvent multipolaires et multi-niveaux [@wiener_something_2000, 1298-1303 et 1343-1348]. Ce manque de divulgation claire dans ces échanges normatifs soulève une difficulté supplémentaire pour l’étude de la convergence normative. En conclusion, l’évolution des normes est ainsi un phénomène complexe, itératif et dynamique dont les résultats ne peuvent être garantis étant donné la grande variété de facteurs et de mécanismes à l’œuvre tout au long de son cycle de vie.

## Hypothèse

En vertu des travaux empiriques menés sur les traités environnementaux et les normes qu’ils encadrent, il serait attendu que la norme ou définition de déchets soit relativement stable et internalisée, de par les observations de changements mineurs des législations nationales avec l’ajout de dispositions internationales supplémentaires sur le sujet [@brandi_when_2019, 31], le manque de profondeur estimé des ententes sur la pollution transfrontalière [@downs_is_1996, 391] et la courbe normale suivie par les enjeux relatifs aux déchets quant à leur diffusion [@busch_international_2005, 86]. L’hypothèse qui dirige cet essai concernant l’évolution de la définition de déchets en tant que norme va comme suit : la définition de déchets est une norme fortement internalisée et peu contestée.

## Stratégie méthodologique

### Cas à l’étude

L’émergence de normes de même que leur adoption et leur application peuvent être difficiles à réaliser sans un régime réglementaire explicite les encadrant. Certains changements normatifs à grande échelle ont été perçus comme des vagues surprises de changements de par le manque d’encadrement permettant une collecte de documentation nécessaire pour un tel suivi [@busch_global_2005, 146-148]. En effet, les normes, dû à leur nature non réglementaire, ne génèrent pas nécessairement de preuve directe de leur présence, mais puisqu’elles demandent une justification quant à leur adoption ou non, particulièrement dans le cadre d’institutions internationales, leur mise en œuvre ou son absence sera soutenue par de la documentation et des communications, elles souvent relativement substantielles [@finnemore_international_1998, 892]. Par le fait même, pour arriver à avoir le matériel nécessaire pour étudier l’évolution de norme de déchets dans l’écosystème internationale, il apparaît tout indiqué de sélectionner comme cas d’étude une convention gérée par une organisation, mais surtout une convention qui comporte des exigences déclaratoires nationales, souvent appelées national reporting, comme c’est le cas pour le présent cas d’étude. Faute de pouvoir observer directement le comportement de chaque des États ratificateurs, l’observation de la documentation qu’ils soumettent dans le cadre de ces procédures constituent un proxy recommandé en recherche [@finnemore_international_1998, 901].

Le cas à l’étude dans le cadre de cet essai est ainsi la Convention de Bâle sur le contrôle des mouvements transfrontières de déchets dangereux et de leur élimination, ci-dessous comprise comme la Convention. Ratifiée en 1989 et entrée en vigueur en 1992, la Convention avait pour objectif d’encadrer la gestion internationale des déchets considérés comme dangereux, tout d’abord en s’attardant sur les déplacements transfrontaliers de ceux-ci, pour garantir une sécurité à tous les États par l’adoption de normes et de procédures communes. En effet, la Convention est rédigée en réponse directe à des évènements de dumping illégal de déchets et autres matières dangereuses dans des pays qualifiés comme en développement à l’époque. Avec la diversification des formes de déchets et des problématiques vécus par ses membres, ceux-ci se comptant au nombre de 191 pays, la Convention a élargie sa portée à tous les déchets, en précisant des exigences particulières en fonction de leur dangerosité, ajoutant notamment à son giron la question des déchets plastiques, des déchets électroniques ou e-waste, des déchets domestiques et autres, étant donné un souci manifeste de la Convention de maintenir un dynamisme et une pertinence face au renouvellement des enjeux de matières résiduelles [@peiry_basel_2013, 434; @secretariat_of_the_basel_convention_history_nodate; @setiawan_basel_2024].

Outre sa portée manifestement englobante sur la question des déchets, la pertinence de la Convention comme cas d’étude se trouve dans le caractère incontournable de son contenu dans le régime international des déchets, étant la plus ancienne convention sur la gestion des déchets non élaborée pour prévenir la pollution marine et la seule qui porte directement sur la gestion et étant celle dont la définition de déchets est la plus reprise dans les conventions subséquentes ou régionales. Composante essentielle de plusieurs autres types d’ententes internationales et convention dynamique dont les COP et les OEWG sont particulièrement productives au niveau technique et normatif, la Convention de Bâle apparaît comme la cheffe de file de la gestion internationale des déchets et ainsi la pierre angulaire des relations internationales en la matière à étudier en cas de changements dans les préoccupations environnementales et les paradigmes de consommation et de production [@noauthor_international_2024; @peiry_basel_2013, 434]. De plus, l’efficacité des changements législatifs peut prendre du temps à se manifester, ceux-ci étant longs à exécuter; une transition de la théorie à la pratique pour une disposition normative peut prendre plus d’une décennie [@berkowitz_transplant_2003, 164-165]. La Convention répond à ces exigences temporelles, son entrée en force datant de 35 ans et son plus récent changement paradigmatique, le passage d’une insistance sur la gestion à la réduction des déchets par la Déclaration de Carthagène, datant de 2011, soit bientôt 15 ans [@secretariat_of_the_basel_convention_cartagena_2011].

### Collecte des données

L’ensemble des données collectées provient des informations soumises par les États ratificateurs au Secrétariat de la Convention à travers le mécanisme de rapportage national. Quatre types de données ont été collectées, soit le nom des Parties de la Convention, les statuts des États dans la Convention, les définitions nationales de la notion de déchets et le nombre de mesures législatives adoptées par les États pour assurer le respect de la Convention sur leur territoire. Les données relatives aux Parties de la Convention et au statut de celles-ci sont collectées à des fins descriptives et ne font pas l’objet d’un codage ou d’une analyse en soit.

### Analyse des données

Concernant les définitions nationales de la notion de déchets, celles-ci font l’objet d’une analyse mixte en deux temps. Un premier codage sur les définitions est réalisé à partir de la correspondance des données avec la définition de la notion de déchets de la Convention de Bâle, qui va comme suit : «Article 2.1. “Wastes” are substances or objects which are disposed of or are intended to be disposed of or are required to be disposed of by the provisions of national law;» [@secretariat_of_the_basel_convention_basel_2023, 7]. Chacune des définitions soumises par les États est codée en fonction de sa correspondance avec la définition de la convention qui comprend trois éléments : le fait de s’en être départi, l’intention de s’en départir et l’obligation de s’en départir. Une absence de déclaration d’une définition serait codée -1, tandis qu’une déclaration d’absence de définition serait codée 0. Si la définition déclarée est équivalente, celle-ci est codée 1. Si la définition déclarée va au-delà de ce qui est spécifié au sein de la définition de la Convention, celle-ci est codée 2. Une fois ce codage réalisé, la distribution géographique des niveaux de définitions est observée pour déterminer l’origine des changements et de la stabilité de la définition de la notion de déchets.

#### Tableau 1 : Explication du système de cotes pour les définitions nationales de déchets

| **Cotes**| **Critères pour l’assignation**|
|:-----|:---------------------------|
|-1| Aucune information n’a été transmis par l’État.|
|0| L’État a déclaré ne pas avoir de définition de la notion de déchets.|
|1| L’État a déclaré avoir une définition de la notion de déchets. La définition est formulée de telle sorte qu’elle reprend textuellement celle de la Convention ou est formulée autrement, mais ne présente que les trois éléments de celle de la Convention.|
|2| L’État a déclaré avoir une définition de la notion de déchets. La définition est formulée de telle sorte qu’elle présente des ajouts conceptuels ou des exigences supplémentaires en comparaison avec celle de la Convention.|

Une fois cette première couche d’analyse des définitions nationales réalisée, les définitions dont le niveau de définition est supérieur à celui de la Convention sont reprises pour un codage supplémentaire à travers une typologisation des concepts ajoutés. Une analyse quantitative de la récurrence des concepts est finalement réalisée.









## References

## Appendix
